config/routes.rb
Rails.application.routes.draw do
  resources :contact_details, only: [:new, :create], as: :contact_details
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
end

app/models/contact_details.rb
class ContactDetails
  include ActiveModel::Model

  # NOTE: Only real reason to use these validations is for simple_form.
  #
  # Duplicating validation is usually a code smell
  #
  validates_presence_of :name
  validates_presence_of :business_name
  validates_presence_of :telephone_number

  # Mandatory user input
  attr_accessor :access_token
  attr_accessor :pGUID
  attr_accessor :pPartner
  attr_accessor :pAccName

  # Optional user input
  attr_accessor :name
  attr_accessor :business_name
  attr_accessor :telephone_number
  attr_accessor :email
  attr_accessor :contact_time
  attr_accessor :notes
  attr_accessor :reference

  def self.post(params)
    begin
      response = Customer.new.post(:create, params)
      JSON.parse(response.body)
    rescue ActiveResource::UnauthorizedAccess, ActiveResource::BadRequest => e
      JSON.parse(e.response.body)
    end
  end
end

app/models/customer.rb
class Customer < ActiveResource::Base
  self.site               = "#{ENV['LEAD_API_URI']}/api/v1"

  headers['Content-Type'] = 'application/x-www-form-urlencoded'
  headers['Accept']       = 'application/json'

  private

  #
  # NOTE: API end-point is a non-standard REST API
  # 
  # POST should not accept query parameters and should expect parameter body instead.
  #
  # As this is not the case we overload the below method so that we can make the correct call to our external API
  #
  # "POST /api/v1/create? ..."
  #
  # A REST API would allow something like "POST /api/v1/leads.json"
  #
  # It seems that the API is not idempotent either, so duplicate entries would be an issue. In these cases we would
  # expect a HTTP status code of 409 though so far I've been unable to replicate this.
  #

  def custom_method_new_element_url(method_name, options = {})
    "#{self.class.prefix(prefix_options)}#{method_name}#{self.class.__send__(:query_string, options)}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_details_controller.rb
class ContactDetailsController < ApplicationController
  def new
    @contact_details = ContactDetails.new
  end

  def create
    @contact_details = ContactDetails.new(contact_details_params)
    @response = ContactDetails.post(contact_details_params.merge(auth_params))

    render :new
  end

  private

  def contact_details_params
    params
      .require(:contact_details)
      .permit(
        :name,
        :business_name,
        :telephone_number,
        :email,
        :contact_time,
        :notes,
        :reference
    )
  end

  #
  # NOTE: Ideally these should be aprt of the API headers and not passed as part of the main payload. So we keep them
  # seperate for to make it clear they are used for authentication and authorisation.
  #
  def auth_params
    {
      access_token: ENV['LEAD_API_ACCESS_TOKEN'],
      pGUID: ENV['LEAD_API_PGUID'],
      pAccName: ENV['LEAD_API_PACCNAME'],
      pPartner: ENV['LEAD_API_PPARTNER']
    }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contact_details/new.html.erb
<section id="contact">
  <% if @response %>
    <section class='message'>
      <% if not @response['errors'].empty? %>
        <div class="alert alert-danger">
          <%= @response['message'] %>
        </div>
        <% else %>
        <div class="alert alert-success">
          <%= @response['message'] %>
        </div>
      <% end %>
    </section>
  <% end %>

  <%= simple_form_for @contact_details, url: contact_details_path, method: :post, html: {class: 'horizontal-form'} do |f| %>
    <%= f.input :name, html: { class: 'col-4' } %>
    <%= f.input :business_name %>
    <%= f.input :telephone_number %>
    <%= f.input :email %>
    <%= f.input :contact_time %>
    <%= f.input :notes %>
    <%= f.input :reference %>

    <% if @response && @response['errors'] %>
      <ul class="alert">
        <% @response['errors'].each do |error| %>
          <li class="alert alert-danger"><%= error %></li>
        <% end %>
      </ul>
    <% elsif @response && @response['message'] %>
      <div class="alert alert-success">
        <%= @response['message'] %>
      </div>
    <% end %>

    <%= f.submit %>
  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" media="all" href="<%= asset_path "application", type: :stylesheet %>" />
    <script src="<%= asset_path "application", type: :javascript %>"></script>

    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700,800' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <section class="container">
      <%= yield %>
    </section>

  </body>
</html>